=== KshiraPradhan/ProgrammingLanguages/XML/Snippets/SDJN/Lab1/src/jlc.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT jlc(student*,course)>
<!ELEMENT student(sname,email+)>
<!ELEMENT course(cname,cost,faculty)>
<!ELEMENT sname(#PCATA)>
<!ELEMENT email(oemail,pemail)>
<!ELEMENT oemail(#PCDATA)>
<!ELEMENT pemail(#PCDATA)>
<!ELEMENT cname(#PCDATA)>
<!ELEMENT cost(#PCDATA)>

<!ATTLIST student
sid CDATA #REQUIRED
job CDATA #IMPLIED>

<!ENTITY f1 "&#233;" >
<!ENTITY company "&#233;" >

=== KshiraPradhan/ProgrammingLanguages/XML/Snippets/SDJN/Lab1.1/src/jlc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jlc SYSTEM "jlc.dtd">
<jlc>
<student sid="11" job="yes">
	<sname>sri</sname>
	<email>
		<oemail>sri@jlc.com</oemail>
		<pemail>gg@jlc.com</pemail>
	</email>
</student>
<course cid="101" free="true">
		<cname>XML</cname>
		<cost>101</cost>
		<faculty>&f1;</faculty>
</course>
</jlc>

=== KshiraPradhan/ProgrammingLanguages/XML/Snippets/SDJN/Lab1/src/jlc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE JLC SYSTEM "jlc.dtd">
<jlc>
	<student sid="11" job="yes">
		<sname>sri</sname>	
		<email>
		<oemail>sri@jl.com</oemail>
		<pemail>ga@jl.com</pemail>
		</email>
	</student>
	<student sid="12" job="no">
		<sname>vas</sname>	
		<email>
		<oemail>sdf@jl.com</oemail>
		<pemail>dfd@jl.com</pemail>
		</email>
	</student>
	<course cid="101" free="yes">
		<cname>XML</cname>
		<cost>500</cost>
		<faculty>&f1;</faculty>
	</course>
	<course cid="102">
		<cname>WS</cname>
		<cost>4500</cost>
		<faculty>&f1;</faculty>
	</course>		
</jlc>
